#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR_OVERRIDE:-$SCRIPT_DIR}"
ENV_FILE="$INSTALL_DIR/.env"
VENV_DIR="$INSTALL_DIR/venv"
SERVER_DATA_DIR="$INSTALL_DIR/server/data"
PORT="${PORT:-8000}"

BOLD='\033[1m'
RESET='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'

NON_INTERACTIVE=false
RUN_SERVER=false
DOCKER_MODE=false
FORCE_ENV=false
SKIP_VENV=false
SKIP_INSTALL=false
SKIP_MIGRATE=false
SKIP_SMOKE=false
SERVER_URL_OVERRIDE=""
SECRET_KEY_OVERRIDE=""
DATABASE_URL_OVERRIDE=""
DOCKER_COMPOSE_CMD=()

info() { echo -e "${BLUE}$*${RESET}"; }
success() { echo -e "${GREEN}$*${RESET}"; }
warn() { echo -e "${YELLOW}$*${RESET}"; }
fail() { echo -e "${RED}$*${RESET}" >&2; exit 1; }

usage() {
    cat <<EOF
UrlTrack automagick installer

Usage:
  ./install.sh [options]

Options:
  -y, --yes                Non-interactive mode, use sensible defaults
  --run                    Start local dev server when setup completes
  --docker                 Prepare Docker setup instead of local Python setup
  --force-env              Recreate .env even if it already exists
  --skip-venv              Do not create the Python virtualenv
  --skip-install           Do not install Python dependencies
  --skip-migrate           Do not run flask db upgrade
  --skip-smoke             Do not run create_app smoke check
  --port PORT              Local port for generated SERVER_URL and --run
  --server-url URL         Override SERVER_URL when creating .env
  --secret-key VALUE       Override SECRET_KEY when creating .env
  --database-url URL       Override DATABASE_URL when creating .env
  -h, --help               Show this help message

Examples:
  ./install.sh --run
  ./install.sh --docker --run
  ./install.sh --yes
  ./install.sh --yes --force-env --server-url http://127.0.0.1:8181
EOF
}

generate_secret_key() {
    python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
}

prompt_with_default() {
    local prompt="$1"
    local default_value="$2"
    local result=""
    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        printf '%s' "$default_value"
        return 0
    fi
    read -r -p "$prompt [$default_value]: " result
    printf '%s' "${result:-$default_value}"
}

prompt_optional() {
    local prompt="$1"
    local result=""
    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        printf '%s' ""
        return 0
    fi
    read -r -p "$prompt" result
    printf '%s' "$result"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

resolve_docker_compose() {
    if docker compose version >/dev/null 2>&1; then
        DOCKER_COMPOSE_CMD=(docker compose)
        return 0
    fi
    if command -v docker-compose >/dev/null 2>&1; then
        DOCKER_COMPOSE_CMD=(docker-compose)
        return 0
    fi
    fail "Docker Compose not found"
}

write_env_file() {
    local secret_key="$1"
    local server_url="$2"
    local database_url="$3"
    local gemini_api_key="$4"
    local gemini_model="$5"
    local telegram_bot_token="$6"
    local telegram_chat_id="$7"
    local turnstile_site="$8"
    local turnstile_secret="$9"

    cat >"$ENV_FILE" <<EOF
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
SECRET_KEY=$secret_key
SERVER_URL=$server_url
DATABASE_URL=$database_url

GEMINI_API_KEY=$gemini_api_key
GEMINI_MODEL=$gemini_model

ANONYMIZE_IP=true
VISIT_RETENTION_DAYS=90
TRUST_PROXY_HEADERS=false
CSP_STRICT=true
SESSION_COOKIE_SECURE=false
REQUIRE_VISIT_TOKEN=true
VISIT_TOKEN_TTL_SECONDS=3600
REQUIRE_CONSENT=false
ALLOW_PARTIAL_EMAIL_CAPTURE=false
CONSENT_TTL_DAYS=180
MASK_WITH_ISGD=false

TELEGRAM_BOT_TOKEN=$telegram_bot_token
TELEGRAM_CHAT_ID=$telegram_chat_id
WEBHOOK_URL=
WEBHOOK_SECRET=
SMART_FOLLOWUP_HOURS=48

TURNSTILE_SITE_KEY=$turnstile_site
TURNSTILE_SECRET_KEY=$turnstile_secret

RATE_LIMIT_REDIRECT=60 per minute
RATE_LIMIT_AUTH=10 per minute
SKIP_BACKGROUND_WORKER=false
MALICIOUS_IP_REFRESH_SECONDS=21600
MALICIOUS_IP_MIN_COUNT=1000
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -y|--yes)
            NON_INTERACTIVE=true
            ;;
        --run)
            RUN_SERVER=true
            ;;
        --docker)
            DOCKER_MODE=true
            ;;
        --force-env)
            FORCE_ENV=true
            ;;
        --skip-venv)
            SKIP_VENV=true
            ;;
        --skip-install)
            SKIP_INSTALL=true
            ;;
        --skip-migrate)
            SKIP_MIGRATE=true
            ;;
        --skip-smoke)
            SKIP_SMOKE=true
            ;;
        --port)
            shift
            [[ $# -gt 0 ]] || fail "--port requires a value"
            PORT="$1"
            ;;
        --server-url)
            shift
            [[ $# -gt 0 ]] || fail "--server-url requires a value"
            SERVER_URL_OVERRIDE="$1"
            ;;
        --secret-key)
            shift
            [[ $# -gt 0 ]] || fail "--secret-key requires a value"
            SECRET_KEY_OVERRIDE="$1"
            ;;
        --database-url)
            shift
            [[ $# -gt 0 ]] || fail "--database-url requires a value"
            DATABASE_URL_OVERRIDE="$1"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "Unknown option: $1"
            ;;
    esac
    shift
done

require_command python3

cd "$INSTALL_DIR"
mkdir -p "$SERVER_DATA_DIR"

printf "${BOLD}UrlTrack automagick installer${RESET}\n"
info "Workspace: $INSTALL_DIR"

if [[ "$DOCKER_MODE" == "true" ]]; then
    require_command docker
    resolve_docker_compose
fi

DEFAULT_SECRET_KEY="${SECRET_KEY_OVERRIDE:-$(generate_secret_key)}"
DEFAULT_SERVER_URL="${SERVER_URL_OVERRIDE:-http://127.0.0.1:$PORT}"
DEFAULT_DATABASE_URL="${DATABASE_URL_OVERRIDE:-sqlite:////$SERVER_DATA_DIR/ulrtrack.db}"
DEFAULT_GEMINI_MODEL="gemini-2.0-flash"
SERVER_URL_DISPLAY="$DEFAULT_SERVER_URL"

if [[ -f "$ENV_FILE" && "$FORCE_ENV" == "true" ]]; then
    cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
    warn ".env exists: backup created, regenerating file"
fi

if [[ ! -f "$ENV_FILE" || "$FORCE_ENV" == "true" ]]; then
    echo ""
    echo -e "${BOLD}Generating .env${RESET}"

    SECRET_KEY_VALUE="$(prompt_with_default "  SECRET_KEY" "$DEFAULT_SECRET_KEY")"
    SERVER_URL_VALUE="$(prompt_with_default "  SERVER_URL" "$DEFAULT_SERVER_URL")"
    DATABASE_URL_VALUE="$(prompt_with_default "  DATABASE_URL" "$DEFAULT_DATABASE_URL")"

    echo ""
    echo -e "${BOLD}Gemini (optional — press Enter to skip)${RESET}"
    GEMINI_API_KEY_VALUE="$(prompt_optional "  GEMINI_API_KEY: ")"
    GEMINI_MODEL_VALUE="$(prompt_with_default "  GEMINI_MODEL" "$DEFAULT_GEMINI_MODEL")"

    echo ""
    echo -e "${BOLD}Telegram alerts (optional — press Enter to skip)${RESET}"
    TELEGRAM_BOT_TOKEN_VALUE="$(prompt_optional "  TELEGRAM_BOT_TOKEN: ")"
    TELEGRAM_CHAT_ID_VALUE="$(prompt_optional "  TELEGRAM_CHAT_ID:    ")"

    echo ""
    echo -e "${BOLD}Cloudflare Turnstile captcha (optional — press Enter to skip)${RESET}"
    echo "  Get keys at: https://dash.cloudflare.com → Turnstile"
    TURNSTILE_SITE_VALUE="$(prompt_optional "  TURNSTILE_SITE_KEY:   ")"
    TURNSTILE_SECRET_VALUE="$(prompt_optional "  TURNSTILE_SECRET_KEY: ")"

    write_env_file \
        "$SECRET_KEY_VALUE" \
        "$SERVER_URL_VALUE" \
        "$DATABASE_URL_VALUE" \
        "$GEMINI_API_KEY_VALUE" \
        "$GEMINI_MODEL_VALUE" \
        "$TELEGRAM_BOT_TOKEN_VALUE" \
        "$TELEGRAM_CHAT_ID_VALUE" \
        "$TURNSTILE_SITE_VALUE" \
        "$TURNSTILE_SECRET_VALUE"

    SERVER_URL_DISPLAY="$SERVER_URL_VALUE"
    success ".env created at $ENV_FILE"
else
    EXISTING_SERVER_URL="$(grep -E '^SERVER_URL=' "$ENV_FILE" | tail -n 1 | cut -d'=' -f2- || true)"
    if [[ -n "$EXISTING_SERVER_URL" ]]; then
        SERVER_URL_DISPLAY="$EXISTING_SERVER_URL"
    fi
    success "Using existing .env at $ENV_FILE"
fi

if [[ "$DOCKER_MODE" == "true" ]]; then
    echo ""
    success "Docker mode ready."
    echo "  1. SQLite data stays in $SERVER_DATA_DIR"
    echo "  2. Container will run Alembic upgrade on boot"
    echo "  3. App will be available on http://127.0.0.1:8000"

    if [[ "$RUN_SERVER" == "true" ]]; then
        echo ""
        info "Starting Docker stack with ${DOCKER_COMPOSE_CMD[*]} up --build"
        exec "${DOCKER_COMPOSE_CMD[@]}" up --build
    fi

    echo ""
    echo -e "${BOLD}Next commands${RESET}"
    echo "  ${DOCKER_COMPOSE_CMD[*]} up --build"
    echo "  or"
    echo "  ${DOCKER_COMPOSE_CMD[*]} up -d --build"
    exit 0
fi

PYTHON_BIN="$VENV_DIR/bin/python"
PIP_BIN="$VENV_DIR/bin/pip"

if [[ "$SKIP_VENV" != "true" ]]; then
    if [[ ! -d "$VENV_DIR" ]]; then
        info "Creating virtualenv..."
        python3 -m venv "$VENV_DIR"
    else
        success "Virtualenv already present"
    fi
else
    warn "Skipping virtualenv creation"
fi

if [[ ! -x "$PYTHON_BIN" ]]; then
    fail "Python interpreter not found at $PYTHON_BIN"
fi

if [[ "$SKIP_INSTALL" != "true" ]]; then
    info "Installing Python dependencies..."
    "$PYTHON_BIN" -m pip install --upgrade pip
    "$PIP_BIN" install -r "$INSTALL_DIR/server/requirements.txt"
    success "Dependencies installed"
else
    warn "Skipping dependency installation"
fi

if [[ "$SKIP_MIGRATE" != "true" ]]; then
    info "Running database migrations..."
    SKIP_BACKGROUND_WORKER=1 "$PYTHON_BIN" -m flask --app server:create_app db upgrade
    success "Database upgraded"
else
    warn "Skipping database migrations"
fi

if [[ "$SKIP_SMOKE" != "true" ]]; then
    info "Running app smoke check..."
    SKIP_BACKGROUND_WORKER=1 "$PYTHON_BIN" -c "from server import create_app; create_app(); print('OK')"
    success "App smoke check passed"
else
    warn "Skipping app smoke check"
fi

echo ""
success "UrlTrack is installed."
echo "  1. Open $SERVER_URL_DISPLAY/setup on first boot"
echo "  2. Create the first admin account"
echo "  3. Save the one-time admin secret code"

if [[ "$RUN_SERVER" == "true" ]]; then
    echo ""
    info "Starting local server on http://127.0.0.1:$PORT"
    exec "$PYTHON_BIN" -m flask --app server:create_app run --host=127.0.0.1 --port="$PORT"
fi

echo ""
echo -e "${BOLD}Next commands${RESET}"
echo "  ./run.sh"
echo "  or"
echo "  $PYTHON_BIN -m flask --app server:create_app run --host=127.0.0.1 --port=$PORT"
