"""lead_visit_complete

Revision ID: 4e4c9a697305
Revises: 9c4e1cb4d4b1
Create Date: 2026-04-14 12:16:41.330832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4c9a697305'
down_revision = '9c4e1cb4d4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('primary_canvas_hash', sa.String(length=64), nullable=True),
    sa.Column('primary_ip', sa.String(length=45), nullable=True),
    sa.Column('all_canvas_hashes', sa.Text(), nullable=True),
    sa.Column('all_ips', sa.Text(), nullable=True),
    sa.Column('all_slugs_visited', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('org', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('os_family', sa.String(length=64), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_primary_canvas_hash'), ['primary_canvas_hash'], unique=False)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_complete', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('visit_complete')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_primary_canvas_hash'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))

    op.drop_table('lead')
    # ### end Alembic commands ###
