"""baseline

Revision ID: fd60bee6230d
Revises: 
Create Date: 2026-04-11 11:32:59.425093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd60bee6230d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=2048), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('enable_captcha', sa.Boolean(), nullable=False),
    sa.Column('max_clicks', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_minutes', sa.Integer(), nullable=False),
    sa.Column('ios_url', sa.String(length=2048), nullable=True),
    sa.Column('android_url', sa.String(length=2048), nullable=True),
    sa.Column('safe_url', sa.String(length=2048), nullable=True),
    sa.Column('block_vpn', sa.Boolean(), nullable=False),
    sa.Column('block_bots', sa.Boolean(), nullable=False),
    sa.Column('allow_no_js', sa.Boolean(), nullable=False),
    sa.Column('schedule_start_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_end_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_timezone', sa.String(length=64), nullable=False),
    sa.Column('block_adblock', sa.Boolean(), nullable=False),
    sa.Column('allowed_countries', sa.String(length=50), nullable=True),
    sa.Column('public_masked_url', sa.String(length=512), nullable=True),
    sa.Column('require_email', sa.Boolean(), nullable=False),
    sa.Column('email_policy', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('setup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('admin_secret_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('passkey_credentials', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('os_family', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('isp', sa.String(length=128), nullable=True),
    sa.Column('org', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('screen_res', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('browser_bot', sa.Boolean(), nullable=False),
    sa.Column('browser_language', sa.String(length=32), nullable=True),
    sa.Column('adblock', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.String(length=512), nullable=True),
    sa.Column('canvas_hash', sa.String(length=64), nullable=True),
    sa.Column('webgl_renderer', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('battery_level', sa.String(length=20), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('etag', sa.String(length=64), nullable=True),
    sa.Column('fpjs_confidence', sa.Float(), nullable=True),
    sa.Column('detected_sessions', sa.Text(), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('is_hosting', sa.Boolean(), nullable=False),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_index('ix_visit_canvas_hash', ['canvas_hash'], unique=False)
        batch_op.create_index('ix_visit_email', ['email'], unique=False)
        batch_op.create_index('ix_visit_etag', ['etag'], unique=False)
        batch_op.create_index('ix_visit_ip', ['ip_address'], unique=False)
        batch_op.create_index('ix_visit_link_id_ts', ['link_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index('ix_visit_link_id_ts')
        batch_op.drop_index('ix_visit_ip')
        batch_op.drop_index('ix_visit_etag')
        batch_op.drop_index('ix_visit_email')
        batch_op.drop_index('ix_visit_canvas_hash')

    op.drop_table('visit')
    op.drop_table('user')
    op.drop_table('setup_state')
    op.drop_table('link')
    # ### end Alembic commands ###
