[ulrtrack-auth]
enabled = true
port = http,https
filter = ulrtrack-auth
logpath = /var/log/nginx/access.log
maxretry = 10
findtime = 600
bantime = 3600

[ulrtrack-scan]
enabled = true
port = http,https
filter = ulrtrack-scan
logpath = /var/log/nginx/access.log
maxretry = 20
findtime = 600
bantime = 7200
